os: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  #- ps: "Get-ChildItem Env:"
  # - "python -m pip install -U pip"
  # - "python --version"
  # - "python -c \"import struct; print(struct.calcsize('P') * 8, 'bits')\""
  # - "pip --version"
  # - ps: "Measure-Command {pip install -r requirements.txt}"
  # - "pip list"
  - "echo ----- NEW VENV -----"
  - "python -m venv v"
  - v\\Scripts\\python -c "from pip._internal.utils.appdirs import user_cache_dir; print(user_cache_dir('pip'), user_cache_dir('wheel'))"
  - "dir /s C:\\Users\\appveyor\\AppData\\Local\\pip\\Cache"
  - "dir /s C:\\Users\\appveyor\\AppData\\Local\\wheel\\Cache"
  - "v\\Scripts\\python -m pip install -U pip"
  - "v\\Scripts\\pip --version"
  - "v\\Scripts\\pip list"
  - ps: "Measure-Command {v\\Scripts\\pip install -r requirements.txt}"
  #- "v\\Scripts\\pip install -v -r requirements.txt"
  - "v\\Scripts\\pip list"
