os: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

build_script:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;;%PATH%"
  - "python -m pip install -U pip"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8, 'bits')\""
  - "pip --version"
  - ps: "Measure-Command {pip install -r requirements.txt}"
  - "pip list"
