trigger:
- master

jobs:
- job: Regular
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - task: PowerShell@2
    inputs:
      filePath: install.ps1

- job: UseVenv
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'
  - task: PowerShell@2
    inputs:
      filePath: install.ps1
      arguments: -UseVenv
